INSERT INTO extensions (version,
                                slug,
                                name,
                                review,
                                description,
                                category,
                                badge,
                                zip_url,
                                price_id,
                                installed,
                                created_at,
                                updated_at,
                                image_url,
                                detail,
                                licensed,
                                price,
                                fake_price)
VALUES (
        'v2',
        'cloudflare-r2',
        'Cloudflare R2',
        5,
        'Cloudflare r2 integration.',
        'Secure, Flexible, Lightning-Fast',
        ' ',
        'zip_url',
        'price_1Oh4fKHSne0x2LpETQzPBQCE',
        0,
        '2024-02-20 07:22:50',
        '2024-03-06 12:17:00',
        'https://api.liquid-themes.com/magicai/extensions/icons/cloudflare-r2.png',
        'With Cloudflare seamlessly integrated into MagicAI, you can trust that your files, documents, and sensitive data are stored securely in the cloud. As your business grows and your data needs expand, rest assured that different storage platforms can effortlessly handle increasing demands, thanks to Cloudflare’s scalable infrastructure. Experience enhanced security, lightning-fast performance, and limitless scalability with MagicAI & CloudFlare.',
        0,
        29,
        39);
